spring:
  datasource:
    url: jdbc:mysql://localhost:3306/selfStudy
    username: selfStudy
    password: selfStudyPw
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      # api의 모든 요청의 기본 경로를 지정
      base-path: /api
      # 클라이언트가 따로 페이지 크기를 요청하지 않을 떄 적용할 기본 페이지 크기를 설정
      default-page:size: 10
      # 최대 페이지 수를 설정
      max-page-size: 10
server:
  port: 8081